### ISSUE TITLE
Update on nodejs-less rpm provided on https://beaker-project.org/yum/server/RedHatEnterpriseLinux7/ is necessary

### ISSUE THREAD

**Issue by desnesn** [beaker-project/beaker-project.org#38]
Hello Beaker Upstream community,

By using an updated version of nodejs on an updated RHEL-7.9.z, beakerd is not being able to start due to a deprecated function in the nodejs-less packaged provided at https://beaker-project.org/yum/server/RedHatEnterpriseLinux7/

Since the code for these packages doesn't seem to be online on your git repos, I am not able to submit a MR with the changes Diego Domingos and I did to backport an upstream less patch on your nodejs-less package.

### SPEC CHANGE
```
--- SPECS/nodejs-less.spec      2022-02-21 14:25:43.291193088 -0500
+++ SPECS/nodejs-less.spec      2022-02-21 14:27:28.214347721 -0500
@@ -2,7 +2,7 @@

 Name:           nodejs-less
 Version:        1.7.0
-Release:        2%{?dist}
+Release:        3%{?dist}
 Summary:        Less.js The dynamic stylesheet language

 # cssmin.js is licensed under BSD license
@@ -15,6 +15,7 @@ Source0: http://registry.npmjs.org/less/
 # Since we're installing this in a global location, fix the require()
 # calls to point there.
 Patch0001: 0001-Require-include-files-from-the-default-location.patch
+Patch0002: 0002-lessc-util.print-has-been-deprecated.patch

 BuildArch:      noarch
 BuildRequires:  nodejs-devel
@@ -35,6 +36,7 @@ and server-side, with Node.js and Rhino.
 %setup -q -n package

 %patch0001 -p1
+%patch0002 -p1

 # Remove pre-built files from the dist/ directory
 rm -f dist/*.js
@@ -68,6 +70,9 @@ ln -s %{nodejs_sitelib}/less/bin/lessc \


 %changelog
+* Mon Feb 21 2022 Desnes A. Nunes do Rosario <desnesn@linux.ibm.com> - 1.7.0-3
+- lessc: util.print() has been deprecated
+
 * Sat Jun 07 2014 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.7.0-2
 - Rebuilt for https://fedoraproject.org/wiki/Fedora_21_Mass_Rebuild
```

### PATCH BACKPORT
File: 0002-lessc-util.print-has-been-deprecated.patch
```
From 51fe1a2d74e1d8f390445a640ac21a994bf10722 Mon Sep 17 00:00:00 2001
From: "Desnes A. Nunes do Rosario" <desnesn@linux.ibm.com>
Date: Fri, 18 Feb 2022 16:56:06 -0500
Subject: [PATCH] lessc: util.print() has been deprecated

https://nodejs.org/api/deprecations.html#DEP0026

Conflicts:
* Backporting only what's on bin/lessc

Upstream status: https://github.com/less/less.js/commit/1ff24b4c266783823a6971696b5ca5366e626463
commit <1ff24b4c266783823a6971696b5ca5366e626463>
Author: Luke Page <luke.a.page@gmail.com>
Subject: do not use util.print since it is deprecated. Fixes #2081

Fixes the following error:
~~~
Feb 18 13:33:56 foobar beaker-server[13664]: FilterError: less: subprocess returned a non-success result code: 2, stdout=, stderr=(node:13936) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/lib/node_modules/less/package.json' of './lib/less/index'. Please either fix that or report it to the module author
Feb 18 13:33:56 foobar beaker-server[13664]: (Use `node --trace-deprecation ...` to show where the warning was created)
Feb 18 13:33:56 foobar beaker-server[13664]: #033[31mTypeError: sys.print is not a function
Feb 18 13:33:56 foobar beaker-server[13664]:     at /usr/lib/node_modules/less/bin/lessc:386:29
Feb 18 13:33:56 foobar beaker-server[13664]:     at tree.importVisitor.finish [as _finish] (/usr/lib/node_modules/less/parser.js:669:28)
Feb 18 13:33:56 foobar beaker-server[13664]:     at tree.importVisitor.subFinish [as _finish] (/usr/lib/node_modules/less/import-visitor.js:84:47)
Feb 18 13:33:56 foobar beaker-server[13664]:     at tree.importVisitor.subFinish [as _finish] (/usr/lib/node_modules/less/import-visitor.js:84:47)
Feb 18 13:33:56 foobar beaker-server[13664]:     at tree.importVisitor.run (/usr/lib/node_modules/less/import-visitor.js:34:22)
Feb 18 13:33:56 foobar beaker-server[13664]:     at /usr/lib/node_modules/less/import-visitor.js:96:38
Feb 18 13:33:56 foobar beaker-server[13664]:     at fileParsedFunc (/usr/lib/node_modules/less/parser.js:82:17)
Feb 18 13:33:56 foobar beaker-server[13664]:     at /usr/lib/node_modules/less/parser.js:105:29
Feb 18 13:33:56 foobar beaker-server[13664]:     at finish (/usr/lib/node_modules/less/parser.js:669:28)
Feb 18 13:33:56 foobar beaker-server[13664]:     at Object.parse (/usr/lib/node_modules/less/parser.js:677:24)#033[39m
~~~

Signed-off-by: Desnes A. Nunes do Rosario <desnesn@linux.ibm.com>
Signed-off-by: Diego Domingos <diegodo@linux.vnet.ibm.com>
---
 bin/lessc | 11 +++++------
 1 file changed, 5 insertions(+), 6 deletions(-)

diff --git a/bin/lessc b/bin/lessc
index 4c1efb2..2b858ad 100755
--- a/bin/lessc
+++ b/bin/lessc
@@ -2,7 +2,6 @@

 var path = require('path'),
     fs = require('fs'),
-    sys = require('util'),
     os = require('os'),
     mkdirp;

@@ -315,10 +314,10 @@ var ensureDirectory = function (filepath) {

 if (options.depends) {
     if (!outputbase) {
-        sys.print("option --depends requires an output path to be specified");
+        console.log("option --depends requires an output path to be specified");
         return;
     }
-    sys.print(outputbase + ": ");
+    process.stdout.write(outputbase + ": ");
 }

 if (!sourceMapFileInline) {
@@ -349,9 +348,9 @@ var parseLessFile = function (e, data) {
             return;
         } else if (options.depends) {
             for(var file in parser.imports.files) {
-                sys.print(file + " ")
+                process.stdout.write(file + " ")
             }
-            sys.print("\n");
+            console.log("");
         } else {
             try {
                if (options.lint) { writeSourceMap = function() {} }
@@ -383,7 +382,7 @@ var parseLessFile = function (e, data) {
                             console.log('lessc: wrote ' + output);
                         }
                     } else {
-                        sys.print(css);
+                        process.stdout.write(css);
                    }
                }
             } catch (e) {
-- 
1.8.3.1
```

Last, but not least, I assume this bug will be hit on RH's internal Beaker when the server receives a nodejs update; that is, if the internal nodejs-less rpm hasn't received a similar backported fix.

Thanks the Beaker support!

**Comment by p3ck** [comment]
Hello,

I've pinged sgallagh@redhat.com who I believe can rebuild this package for us in epel-7.  I included your patch and spec file update.  When it is update in epel we can then see about getting the rpm pulled into the yum repos hosted here.

Thanks!

**Comment by StykMartin** [comment]
Hi.

@p3ck thank you for taking care of the build. Let me know when the package is ready I will make sure it is available in the upstream repository.

**Comment by p3ck** [comment]
@StykMartin Stephen has built the latest version here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-650bd8199d

Not sure if you can pull it directly from koji or if you need to wait till it moves to the repo?

**Comment by desnesn** [comment]
Hello @p3ck and @StykMartin ,

I was testing a new internal feature which made me notice that the new '''latest nodejs-less4.1.2-1.el7''' breaks beakerd as well, but with a newer bug on the bootstrap calculation of parameters from the variables.less file:

~~~
Mar  9 13:42:10 foobar beaker-server[24779]: bkr.server.controllers INFO Server startup in 0.0587100982666 seconds
Mar  9 13:42:11 foobar beaker-server[24779]: bkr.server ERROR Exception on /client/ [POST]
Mar  9 13:42:11 foobar beaker-server[24779]: Traceback (most recent call last):
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Mar  9 13:42:11 foobar beaker-server[24779]:     response = self.full_dispatch_request()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1470, in full_dispatch_request
Mar  9 13:42:11 foobar beaker-server[24779]:     self.try_trigger_before_first_request_functions()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1497, in try_trigger_before_first_request_functions
Mar  9 13:42:11 foobar beaker-server[24779]:     func()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/bkr/server/wsgi.py", line 120, in init
Mar  9 13:42:11 foobar beaker-server[24779]:     assets.build_assets()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/bkr/server/assets.py", line 170, in build_assets
Mar  9 13:42:11 foobar beaker-server[24779]:     bundle.build()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 567, in build
Mar  9 13:42:11 foobar beaker-server[24779]:     disable_cache=disable_cache))
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 504, in _build
Mar  9 13:42:11 foobar beaker-server[24779]:     force, disable_cache=disable_cache, extra_filters=extra_filters)
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 429, in _merge_and_apply
Mar  9 13:42:11 foobar beaker-server[24779]:     kwargs=item_data)
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/merge.py", line 272, in apply
Mar  9 13:42:11 foobar beaker-server[24779]:     return self._wrap_cache(key, func)
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/merge.py", line 219, in _wrap_cache
Mar  9 13:42:11 foobar beaker-server[24779]:     content = func().getvalue()
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/merge.py", line 252, in func
Mar  9 13:42:11 foobar beaker-server[24779]:     getattr(filter, type)(data, out, **kwargs_final)
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/filter/less.py", line 97, in input
Mar  9 13:42:11 foobar beaker-server[24779]:     self.subprocess(args, out, in_)
Mar  9 13:42:11 foobar beaker-server[24779]:   File "/usr/lib/python2.7/site-packages/webassets/filter/__init__.py", line 505, in subprocess
Mar  9 13:42:11 foobar beaker-server[24779]:     proc.returncode, stdout, stderr))
Mar  9 13:42:11 foobar beaker-server[24779]: FilterError: less: subprocess returned a non-success result code: 1, stdout=, stderr=#033[31mArgumentError: Error evaluating function `percentage`: argument must be a number#033[39m#033[31m in #033[39mbootstrap/less/variables.less#033[90m on line 292, column 27:#033[39m
Mar  9 13:42:11 foobar beaker-server[24779]: #033[90m291 // -------------------------#033[39m
Mar  9 13:42:11 foobar beaker-server[24779]: 292 @fluidGridColumnWidth:    #033[7m#033[31m#033[1mp#033[22mercentage(@gridColumnWidth/@gridRowWidth);#033[39m#033[27m
Mar  9 13:42:11 foobar beaker-server[24779]: #033[90m293 @fluidGridGutterWidth:    percentage(@gridGutterWidth/@gridRowWidth);#033[39m#033[0m#033[0m
~~~

I guess it has something to do with casting and variable declaration?

On the following file: 

~~~
[root@foobar beaker]# rpm -qf /usr/share/bkr/server/assets/bootstrap/less/variables.less
beaker-server-28.2-1.el7bkr.noarch
~~~

~~~
// Default 940px grid
// -------------------------
@gridColumns:             12;
@gridColumnWidth:         60px;
@gridGutterWidth:         20px;
@gridRowWidth:            (@gridColumns * @gridColumnWidth) + (@gridGutterWidth * (@gridColumns - 1));

...

// Fluid grid
// -------------------------
--> @fluidGridColumnWidth:    percentage(@gridColumnWidth/@gridRowWidth);
--> @fluidGridGutterWidth:    percentage(@gridGutterWidth/@gridRowWidth);
~~~

Thanks!!

**Comment by StykMartin** [comment]
@desnesn im aware of it. Bump is too big for no reason. I will rebuild latest build with patches.

**Comment by p3ck** [comment]
@StykMartin sorry about that. I even provided the spec and patches that @desnesn provided. I'm not sure why they bumped so high.

Are you able to patch beaker to work with the latest nodejs-less?  Or are you planning to build the older nodejs-less?

**Comment by StykMartin** [comment]
Hi @p3ck. For now, I will build nodejs-less w/ patch, so we can move on. I will put it into a backlog that we have this issue and I may change the beaker to work with latest nodejs-less. 

I expect that the build will be in the repository at end of this week.

**Comment by desnesn** [comment]
Hello @StykMartin - I guess the only thing needed to close this issue is to bring the internal rpm you built to the external https://beaker-project.org/yum/server/RedHatEnterpriseLinux7/ repository, right?

The beaker-project external repo still has the broken version, while the epel still has the big bump v4.1.2-1.el7 version.

Thanks again

**Comment by desnesn** [comment]
If this helps anybody, I made a patched version of the nodejs-less available at my COPR repo:

* https://copr.fedorainfracloud.org/coprs/desnesn/beaker.dn/

Cheers,

**Comment by StykMartin** [comment]
Fixed in
```
Name        : nodejs-less
Arch        : noarch
Version     : 1.7.0
Release     : 6.el7
Size        : 102 k
Repo        : beaker-server/7
Summary     : Less.js The dynamic stylesheet language
URL         : http://lesscss.org
License     : ASL 2.0 and BSD
Description : LESS extends CSS with dynamic behavior such as variables, mixins, operations
            : and functions. LESS runs on both the client-side (Chrome, Safari, Firefox)
            : and server-side, with Node.js and Rhino.

```
